name: Update README with file count

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Count files in repository
        id: count_files
        run: |
          file_count=$(find . -type f | wc -l)
          echo "::set-output name=count::$file_count"

      - name: Update README.md
        run: |
          sed -i 's/<!-- FILE_COUNT -->/${{ steps.count_files.outputs.count }}/' README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update file count in README"
          git push
